WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720

VIRTUAL_WIDTH = 512
VIRTUAL_HEIGHT = 288

SCALE_X = VIRTUAL_WIDTH/WINDOW_WIDTH
SCALE_Y = VIRTUAL_HEIGHT/WINDOW_HEIGHT

PLAYER_SPEED = 100
PLAYER_JUMP_HEIGHT = PLAYER_SPEED * 2
PLAYER_WIDTH = 30
PLAYER_HEIGHT = 30

PLATFORM_SPEED = 70

GRAVITY = 300

DEBUG_MODE = false

MIN_PLATFORM_WIDTH = 10
MIN_PLATFORM_HEIGHT = 10

MAX_PLATFORM_WIDTH = 300
MAX_PLATFORM_HEIGHT = 100